/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import main.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cminh
 */
public class CusAppointmentForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CusAppointmentForm.class.getName());

    private Customer customer;
    private CusDashboardForm dashboard;

    public CusAppointmentForm(Customer customer, CusDashboardForm dashboard) {
        initComponents();
        this.customer = customer;
        this.dashboard = dashboard;
        setTitle("Appointments - " + customer.getName());
        loadAppointments();
        setLocationRelativeTo(null);
    }

    private void loadAppointments() {
        try {
            DefaultTableModel model = (DefaultTableModel) Appointmenttable.getModel();
            model.setRowCount(0);

            for (main.Appointment a : DataIO.allAppointments) {
                if (a.getCustomerUsername().equals(customer.getUsername())
                        && ("Booked".equalsIgnoreCase(a.getStatus())
                        || ("Pending".equalsIgnoreCase(a.getStatus()))
                        || "Cancellation In Progress".equalsIgnoreCase(a.getStatus()))) {

                    Object[] row = {
                        a.getAppointmentId(),
                        a.getDate(),
                        a.getTime(),
                        a.getDoctorUsername(),
                        a.getStaffId(),
                        a.getStatus()
                    };
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading appointments.");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Appointmenttable = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Appointmenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Date", "Time", "Doctor", "Staff ID", "Status"
            }
        ));
        jScrollPane1.setViewportView(Appointmenttable);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Cancel.setText("Request cancellation");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Show.setText("Show All");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Show)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search)
                    .addComponent(Show))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Back))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.dispose();
        if (dashboard != null) {
            dashboard.setVisible(true);
        }
    }//GEN-LAST:event_BackActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        int selectedRow = Appointmenttable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an appointment first.");
            return;
        }

        String apptId = Appointmenttable.getValueAt(selectedRow, 0).toString();
        String status = Appointmenttable.getValueAt(selectedRow, 5).toString();

        if (!status.equalsIgnoreCase("Pending")) {
            JOptionPane.showMessageDialog(this, "Only Pending appointments can be cancelled.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Appointment ID: " + apptId
                + "\nConfirm request cancellation?",
                "Request Cancellation", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                DataIO.updateAppointmentStatus(apptId, "Cancellation In Progress");
                JOptionPane.showMessageDialog(this, "Request submitted.");
                loadAppointments();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error updating appointment.");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_CancelActionPerformed


    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        String keyword = txtSearch.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) Appointmenttable.getModel();
        model.setRowCount(0);

        boolean found = false;

        for (main.Appointment a : DataIO.allAppointments) {
            if (a.getCustomerUsername().equals(customer.getUsername())
                    && ("Booked".equalsIgnoreCase(a.getStatus())
                    || "Pending".equalsIgnoreCase(a.getStatus())
                    || "Cancellation In Progress".equalsIgnoreCase(a.getStatus()))) {

                String apptId = (a.getAppointmentId() == null) ? "" : a.getAppointmentId().toLowerCase();
                String doctor = (a.getDoctorUsername() == null) ? "" : a.getDoctorUsername().toLowerCase();
                String status = (a.getStatus() == null) ? "" : a.getStatus().toLowerCase();

                if (keyword.isEmpty()
                        || apptId.contains(keyword)
                        || doctor.contains(keyword)
                        || status.contains(keyword)) {

                    model.addRow(new Object[]{
                        a.getAppointmentId(),
                        a.getDate(),
                        a.getTime(),
                        a.getDoctorUsername() == null ? "" : a.getDoctorUsername(),
                        a.getStaffId() == null ? "" : a.getStaffId(),
                        a.getStatus() == null ? "Unknown" : a.getStatus()
                    });
                    found = true;
                }
            }
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        loadAppointments();
    }//GEN-LAST:event_ShowActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Appointmenttable;
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Search;
    private javax.swing.JButton Show;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
