/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import main.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*; 

/**
 *
 * @author cminh
 */
public class CusCommentForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CusCommentForm.class.getName());
    private Customer customer;
    private CusDashboardForm dashboard;
    private static java.util.List<String> createdComments = new java.util.ArrayList<>();

    public static void initializeCreatedComments() {
        createdComments.clear();
        for (main.Appointment appt : DataIO.allAppointments) {
            if (appt.getComment() != null && !appt.getComment().isEmpty()) {
                createdComments.add(appt.getAppointmentId());
            }
        }
    }

    /**
     * Creates new form CusCommentForm
     */
    public CusCommentForm(Customer customer, CusDashboardForm dashboard) {
        initComponents();
        this.customer = customer;
        this.dashboard = dashboard;
        setTitle("Comment for Staff and Doctor");
        setLocationRelativeTo(null);
        loadCreatedComments();
        addTableClickListener();
    }

    private void loadCreatedComments() {
        DefaultTableModel model = (DefaultTableModel) Commenttable.getModel();
        model.setRowCount(0);

        if (customer != null) {
            for (main.Appointment a : DataIO.allAppointments) {
                if (a.getCustomerUsername().equals(customer.getUsername())
                        && a.getComment() != null && !a.getComment().isEmpty()
                        && a.getRating() != null) {

                    Object[] row = {
                        a.getAppointmentId(),
                        a.getDoctorUsername(),
                        a.getStaffId(),
                        a.getDate(),
                        a.getTime(),
                        a.getRating(),
                        a.getComment()
                    };
                    model.addRow(row);
                }
            }
        }
    }
        private void addTableClickListener() {
        Commenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = Commenttable.rowAtPoint(evt.getPoint());
                int col = Commenttable.columnAtPoint(evt.getPoint());
                if (row < 0 || col < 0) return;

                String colName = Commenttable.getColumnModel()
                                             .getColumn(col)
                                             .getHeaderValue()
                                             .toString();

                if ("Comment".equalsIgnoreCase(colName)) {
                    Object value = Commenttable.getValueAt(row, col);
                    String text = value == null ? "" : value.toString();

                    JTextArea textArea = new JTextArea(text);
                    textArea.setLineWrap(true);
                    textArea.setWrapStyleWord(true);
                    textArea.setEditable(false);
                    textArea.setCaretPosition(0);

                    JScrollPane scrollPane = new JScrollPane(textArea);
                    scrollPane.setPreferredSize(new Dimension(400, 200));

                    JOptionPane.showMessageDialog(
                        CusCommentForm.this,
                        scrollPane,
                        "Comment Detail",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Commenttable = new javax.swing.JTable();
        Create = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Commenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment ID", "Doctor ", "Staff ID", "Date ", "Time ", "Ratings", "Comment"
            }
        ));
        jScrollPane1.setViewportView(Commenttable);

        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Show.setText("Show All");
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Show)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search)
                    .addComponent(Show))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Create)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        CusCreateComment dialog = new CusCreateComment(customer, (appointmentId) -> {
            loadCreatedComments();
        });
        dialog.setVisible(true);
    }//GEN-LAST:event_CreateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int selectedRow = Commenttable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a comment to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this comment?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            String appointmentId = (String) Commenttable.getValueAt(selectedRow, 0);

            for (main.Appointment appt : DataIO.allAppointments) {
                if (appt.getAppointmentId().equals(appointmentId)) {
                    appt.setFeedback(null);
                    appt.setRating(null);
                    appt.setComment(null);
                    break;
                }
            }

            DataIO.write();

            loadCreatedComments();

            JOptionPane.showMessageDialog(this, "Comment deleted successfully!");
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        int selectedRow = Commenttable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a comment to update.");
            return;
        }

        String appointmentId = (String) Commenttable.getValueAt(selectedRow, 0);

        for (main.Appointment appt : DataIO.allAppointments) {
            if (appt.getAppointmentId().equals(appointmentId)) {
                CusUpdateComment dialog = new CusUpdateComment(customer, appt, (updatedAppt) -> {

                    loadCreatedComments();
                });
                dialog.setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        String keyword = txtSearch.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) Commenttable.getModel();
        model.setRowCount(0);

        for (main.Appointment a : DataIO.allAppointments) {
            if (a.getCustomerUsername().equals(customer.getUsername())
                    && a.getComment() != null && !a.getComment().isEmpty()
                    && a.getRating() != null) {
        String doctor = (a.getDoctorUsername() == null) ? "" : a.getDoctorUsername().toLowerCase();
        String ratingStr = String.valueOf(a.getRating()).toLowerCase();

        if (keyword.isEmpty()
                || a.getAppointmentId().toLowerCase().contains(keyword)
                || doctor.contains(keyword)
                || ratingStr.contains(keyword)) {
            
                    model.addRow(new Object[]{
                        a.getAppointmentId(),
                        (a.getDoctorUsername()== null) ? "" : a.getDoctorUsername(),
                        a.getStaffId(),
                        a.getDate(),
                        a.getTime(),
                        a.getRating(),
                        a.getComment(),});
                }
            }
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        loadCreatedComments();
    }//GEN-LAST:event_ShowActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        if (dashboard != null) {
            dashboard.setVisible(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTable Commenttable;
    private javax.swing.JButton Create;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Search;
    private javax.swing.JButton Show;
    private javax.swing.JButton Update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
