/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctor;

import main.*;
import javax.swing.*;
import java.util.logging.Logger;
import java.time.LocalDate;

/**
 *
 * @author User
 */
public class DoctorDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorDashboard.class.getName());
    private Doctor currentDoctor;

    /**
     * Creates new form DoctorDashboard
     */
    public DoctorDashboard(Doctor doctor) {
        this.currentDoctor = doctor;
        initComponents();
        
         if (currentDoctorLabel != null) {
            currentDoctorLabel.setText(currentDoctor.getUsername());
        } else {
            currentDoctorLabel.setText("-");
        }

        updateDoctorDashboardStats(currentDoctor.getUsername());
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowActivated(java.awt.event.WindowEvent e) {
                updateDoctorDashboardStats(currentDoctor.getUsername());
            }
        });
        setLocationRelativeTo(null);

    }
    
    private void updateDoctorDashboardStats(String doctorId) {
    DataIO.read(); 
    LocalDate todayDate = LocalDate.now();

    int todayCount = 0;
    int upcomingCount = 0;

    for (Appointment a : DataIO.allAppointments) {
        if (a.getDoctorUsername() != null && a.getDoctorUsername().equals(doctorId)) {
            String dateStr = a.getDate();
            if (dateStr == null || dateStr.isEmpty()) continue;
            LocalDate apptDate;
            try {
                apptDate = LocalDate.parse(dateStr);
            } catch (Exception ex) {
                continue;
            }

            String status = a.getStatus() == null ? "" : a.getStatus();
            boolean isCancelled = "cancelled".equalsIgnoreCase(status) || "cancel".equalsIgnoreCase(status);
            boolean isActiveUpcoming = "booked".equalsIgnoreCase(status) || "assigned".equalsIgnoreCase(status) || "pending".equalsIgnoreCase(status);

            if (apptDate.equals(todayDate) && !isCancelled) {
                todayCount++;
            }
            if (apptDate.isAfter(todayDate) && isActiveUpcoming) {
                upcomingCount++;
            }
        }
    }

    todaysAppointmentsLabel.setText(String.valueOf(todayCount));
    pendingAppointmentsLabel.setText(String.valueOf(upcomingCount));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TodaysAppointments = new javax.swing.JLabel();
        todaysAppointmentsLabel = new javax.swing.JLabel();
        PendingAppoinments = new javax.swing.JLabel();
        pendingAppointmentsLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        APUMedicalCentre = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ViewAppointments = new javax.swing.JButton();
        ViewHistories = new javax.swing.JButton();
        EditProfile = new javax.swing.JButton();
        EnterChargesandFeedbacks = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Doctor = new javax.swing.JLabel();
        currentDoctorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TodaysAppointments.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TodaysAppointments.setText("Today's Appointments:");

        todaysAppointmentsLabel.setText("-");

        PendingAppoinments.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PendingAppoinments.setText("Upcoming Appoinments:");

        pendingAppointmentsLabel.setText("-");

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        APUMedicalCentre.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        APUMedicalCentre.setText("APU Medical Centre");

        Logout.setBackground(new java.awt.Color(204, 204, 255));
        Logout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(APUMedicalCentre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(APUMedicalCentre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Logout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ViewAppointments.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewAppointments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/10620193.png"))); // NOI18N
        ViewAppointments.setText("View Appointments");
        ViewAppointments.setPreferredSize(new java.awt.Dimension(173, 22));
        ViewAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAppointmentsActionPerformed(evt);
            }
        });

        ViewHistories.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ViewHistories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3678527.png"))); // NOI18N
        ViewHistories.setText("View Histories");
        ViewHistories.setPreferredSize(new java.awt.Dimension(173, 22));
        ViewHistories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHistoriesActionPerformed(evt);
            }
        });

        EditProfile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5003738.png"))); // NOI18N
        EditProfile.setText("Edit Profile");
        EditProfile.setPreferredSize(new java.awt.Dimension(173, 22));
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });

        EnterChargesandFeedbacks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EnterChargesandFeedbacks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3678698.png"))); // NOI18N
        EnterChargesandFeedbacks.setText("Enter Charges & Feedbacks");
        EnterChargesandFeedbacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterChargesandFeedbacksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewHistories, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(ViewAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterChargesandFeedbacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(EditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewHistories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnterChargesandFeedbacks, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome");

        Doctor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Doctor.setText("Doctor:");

        currentDoctorLabel.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Doctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentDoctorLabel)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Doctor)
                    .addComponent(currentDoctorLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 188, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PendingAppoinments)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pendingAppointmentsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TodaysAppointments)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(todaysAppointmentsLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TodaysAppointments)
                    .addComponent(todaysAppointmentsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PendingAppoinments)
                    .addComponent(pendingAppointmentsLabel))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        JOptionPane.showMessageDialog(this, "You have been logged out.");
        new LoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void ViewAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAppointmentsActionPerformed
        new DoctorViewAppointment(currentDoctor).setVisible(true);
    dispose();
    }//GEN-LAST:event_ViewAppointmentsActionPerformed

    private void EnterChargesandFeedbacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterChargesandFeedbacksActionPerformed
        new EnterChargesFeedbackPage(currentDoctor).setVisible(true);
    dispose();
    }//GEN-LAST:event_EnterChargesandFeedbacksActionPerformed

    private void ViewHistoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHistoriesActionPerformed
        new ViewHistoryPage(currentDoctor).setVisible(true);
    dispose();
    }//GEN-LAST:event_ViewHistoriesActionPerformed

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileActionPerformed
        new EditDocProfile(currentDoctor).setVisible(true);
    dispose();
    }//GEN-LAST:event_EditProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        
        java.awt.EventQueue.invokeLater(() -> {
            Doctor demoDoctor = new Doctor("D0000", "doc1", "1234", "Dr. John", "M",
                                           "john@mail.com", "0123456789", 40);
            new DoctorDashboard(demoDoctor).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APUMedicalCentre;
    private javax.swing.JLabel Doctor;
    private javax.swing.JButton EditProfile;
    private javax.swing.JButton EnterChargesandFeedbacks;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel PendingAppoinments;
    private javax.swing.JLabel TodaysAppointments;
    private javax.swing.JButton ViewAppointments;
    private javax.swing.JButton ViewHistories;
    private javax.swing.JLabel currentDoctorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel pendingAppointmentsLabel;
    private javax.swing.JLabel todaysAppointmentsLabel;
    // End of variables declaration//GEN-END:variables
}
