/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Staff;
import main.User;
import main.*;
/**
 *
 * @author lisha
 */
public class EditStaffProfile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditStaffProfile.class.getName());

    /**
     * Creates new form EditStaffProfile
     */
    private User currentUser;

    public EditStaffProfile(User currentUser) {
        this.currentUser = currentUser;
        initComponents();
        refreshUserData();
        setLocationRelativeTo(null); 
        
        editBtn.addActionListener(e -> {
        EditProfileForm form = new EditProfileForm(this, currentUser);
        form.setVisible(true);
        if (form.isSaved()) {
            refreshUserData();
        }
        });

        backBtn.addActionListener(e -> {
            dispose();
            new StaffDashboard(currentUser).setVisible(true);
        });
    }
    
    private void refreshUserData() {
        staffIdValue.setText(currentUser.getUserId());
        usernameValue.setText(currentUser.getUsername());
        passwordValue.setText(currentUser.getPassword());
        nameValue.setText(currentUser.getName());
        genderValue.setText(currentUser.getGender());
        emailValue.setText(currentUser.getEmail());
        phoneValue.setText(currentUser.getPhone());
        ageValue.setText(String.valueOf(currentUser.getAge()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        staffIdValue = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usernameValue = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameValue = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        genderValue = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailValue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneValue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ageValue = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 568));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(8, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("StaffId:");
        jPanel1.add(jLabel1);

        staffIdValue.setText("-");
        jPanel1.add(staffIdValue);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Username:");
        jPanel1.add(jLabel8);

        usernameValue.setText("-");
        jPanel1.add(usernameValue);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Password:");
        jPanel1.add(jLabel9);

        passwordValue.setText("-");
        jPanel1.add(passwordValue);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);

        nameValue.setText("-");
        jPanel1.add(nameValue);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gender:");
        jPanel1.add(jLabel3);

        genderValue.setText("-");
        jPanel1.add(genderValue);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4);

        emailValue.setText("-");
        jPanel1.add(emailValue);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phone:");
        jPanel1.add(jLabel5);

        phoneValue.setText("-");
        jPanel1.add(phoneValue);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Age:");
        jPanel1.add(jLabel6);

        ageValue.setText("-");
        jPanel1.add(ageValue);

        jLayeredPane2.add(jPanel1);
        jPanel1.setBounds(60, 40, 680, 470);

        editBtn.setText("Edit");
        jLayeredPane2.add(editBtn);
        editBtn.setBounds(280, 530, 72, 23);

        backBtn.setText("Back");
        jLayeredPane2.add(backBtn);
        backBtn.setBounds(420, 530, 72, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(800, 568));
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            User demoUser = new Staff("S0000", "staff1", "123", "Alice", "F", "alice@mail.com", "0123456789", 28);
            new EditStaffProfile(demoUser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageValue;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel emailValue;
    private javax.swing.JLabel genderValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameValue;
    private javax.swing.JLabel passwordValue;
    private javax.swing.JLabel phoneValue;
    private javax.swing.JLabel staffIdValue;
    private javax.swing.JLabel usernameValue;
    // End of variables declaration//GEN-END:variables
}
